### ISSUE TITLE
crash eating a cabbage from The Erebus mod on a server. the Crash say something about Galacticraft

### ISSUE THREAD

**Issue by Alessandro404** [Tmtravlr/MusicChoices#5]
In single player, eating a cabbage (from the erebus mod) make you emit a fart.  I had no issue there, but when i try to make the same on my private server...

Seems that galacticraft doesn't like this mod. If I remove MusicChoices and rejoin the server, I can again eat cabbages, but with MusicChoices...

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 10/20/15 7:27 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
    at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:381)
    at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:311)
    at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:538)
    at net.minecraft.client.entity.EntityPlayerSP.func_70636_d(EntityPlayerSP.java:287)
    at micdoodle8.mods.galacticraft.core.entities.player.GCEntityClientPlayerMP.func_70636_d(GCEntityClientPlayerMP.java:42)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
    at net.minecraft.client.entity.EntityClientPlayerMP.func_70071_h_(SourceFile:63)
    at micdoodle8.mods.galacticraft.core.entities.player.GCEntityClientPlayerMP.func_70071_h_(GCEntityClientPlayerMP.java:62)
    at net.minecraft.world.World.func_72866_a(World.java:2070)
    at net.minecraft.world.World.func_72870_g(World.java:2034)
    at net.minecraft.world.World.func_72939_s(World.java:1887)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:273)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:363)
    at org.multimc.EntryPoint.listen(EntryPoint.java:165)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:381)
    at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:311)
    at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:538)
    at net.minecraft.client.entity.EntityPlayerSP.func_70636_d(EntityPlayerSP.java:287)
    at micdoodle8.mods.galacticraft.core.entities.player.GCEntityClientPlayerMP.func_70636_d(GCEntityClientPlayerMP.java:42)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
    at net.minecraft.client.entity.EntityClientPlayerMP.func_70071_h_(SourceFile:63)
    at micdoodle8.mods.galacticraft.core.entities.player.GCEntityClientPlayerMP.func_70071_h_(GCEntityClientPlayerMP.java:62)
    at net.minecraft.world.World.func_72866_a(World.java:2070)
    at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
    Entity Type: null (micdoodle8.mods.galacticraft.core.entities.player.GCEntityClientPlayerMP)
    Entity ID: 2125292
    Entity Name: Darmin404
    Entity's Exact location: 0.79, 68.62, -3.51
    Entity's Block location: World: (0,68,-4), Chunk: (at 0,4,12 in 0,-1; contains blocks 0,0,-16 to 15,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Entity's Momentum: 0.00, -0.08, 0.00
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1887)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [GCEntityClientPlayerMP['Darmin404'/2125292, l='MpServer', x=0.79, y=68.62, z=-3.51]]
    Chunk stats: MultiplayerChunkCache: 420, 420
    Level seed: 0
    Level generator: ID 04 - TerrainControl, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 9211381 game time, 1753806 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 4 total; [EntityInhabitedZombie['Shambling Husk'/2127302, l='MpServer', x=24.50, y=126.00, z=-35.50], GCEntityClientPlayerMP['Darmin404'/2125292, l='MpServer', x=0.79, y=68.62, z=-3.51], EntityCustomNpc['Zombie common'/2126917, l='MpServer', x=-1.50, y=35.00, z=-46.50], EntityCustomNpc['phantom'/2126919, l='MpServer', x=12.50, y=67.00, z=-7.50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:273)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:363)
    at org.multimc.EntryPoint.listen(EntryPoint.java:165)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.7.0_65, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 817700912 bytes (779 MB) / 1801977856 bytes (1718 MB) up to 1908932608 bytes (1820 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx2048m -XX:PermSize=512m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 Optifine OptiFine_1.7.10_HD_C1 62 mods loaded, 62 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJA  mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJA  FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1492-1.7.10-universal.jar) 
    UCHIJA  Forge{10.13.4.1492} [Minecraft Forge](forge-1.7.10-10.13.4.1492-1.7.10-universal.jar) 
    UCHIJA  appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core](minecraft.jar) 
    UCHIJA  CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar) 
    UCHIJA  ImmibisMicroblocks{59.1.1} [Immibis's Microblocks](immibis-microblocks-59.1.1.jar) 
    UCHIJA  InfiniBows{1.3.0 build 20} [InfiniBows](minecraft.jar) 
    UCHIJA  Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) 
    UCHIJA  NotEnoughItems{1.0.5.118} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
    UCHIJA  OpenComputers|Core{1.5.18.36} [OpenComputers (Core)](minecraft.jar) 
    UCHIJA  adventure_backport_core{2.0.1-alpha} [Adventure Backport Core](minecraft.jar) 
    UCHIJA  bspkrsCore{6.16} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.16.jar) 
    UCHIJA  ArmorStatusHUD{1.28} [ArmorStatusHUD]([1.7.10]ArmorStatusHUD-client-1.28.jar) 
    UCHIJA  StatusEffectHUD{1.27} [StatusEffectHUD]([1.7.10]StatusEffectHUD-client-1.27.jar) 
    UCHIJA  IC2{2.2.782-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.782-experimental.jar) 
    UCHIJA  ImmibisCore{59.1.2} [Immibis Core](immibis-core-59.1.2.jar) 
    UCHIJA  AdvancedRepulsionSystems{59.0.3} [Advanced Repulsion Systems](adv-repulsion-systems-59.0.3.jar) 
    UCHIJA  adventure_backport{2.0-alpha} [Adventure Backport](adventure_backport-2.0.1-alpha.jar) 
    UCHIJA  AmnesiaDecorations{1.1.1} [Amnesia Decorations](AmnesiaDecorations-1.7.10-1.1.1.jar) 
    UCHIJA  AmnesiaLights{1.1.1} [Amnesia Lights](AmnesiaLights-1.7.10-1.1.1.jar) 
    UCHIJA  AmnesiaMonsters{1.1.1} [Amnesia Monsters](AmnesiaMonsters-1.7.10-1.1.1.jar) 
    UCHIJA  appliedenergistics2{rv2-stable-10} [Applied Energistics 2](appliedenergistics2-rv2-stable-10.jar) 
    UCHIJA  Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCHIJA  Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) 
    UCHIJA  Automagy{0.26.3} [Automagy](Automagy-1.7.10-0.26.3.jar) 
    UCHIJA  betterrain{0.15} [Better Rain](betterrain-1.7.2-1.7.10_0.15.jar) 
    UCHIJA  BiblioCraft{1.11.2} [BiblioCraft](BiblioCraft[v1.11.2][MC1.7.10].jar) 
    UCHIJA  TwilightForest{2.3.7} [The Twilight Forest](twilightforest-1.7.10-2.3.7.jar) 
    UCHIJA  chisel{2.5.1.44} [Chisel 2](Chisel2-2.5.1.44.jar) 
    UCHIJA  chocolateQuest{1.0} [Chocolate Quest](chocolateQuest-1.7.10-1.0.jar) 
    UCHIJA  customnpcs{1.7.10c} [CustomNpcs](CustomNPCs_1.7.10c.jar) 
    UCHIJA  DamageIndicatorsMod{3.2.0} [Damage Indicators](Damage-Indicators-Mod-1.7.10.jar) 
    UCHIJA  DimensionInventorys{0.1} [Dimension Inventorys](DimensionInventorys-0.1.jar) 
    UCHIJA  EnderStorage{1.4.7.37} [EnderStorage](EnderStorage-1.7.10-1.4.7.37-universal.jar) 
    UCHIJA  etfuturum{1.4.4} [Et Futurum](Et Futurum-1.4.4.jar) 
    UCHIJA  flansmod{4.10.0} [Flan's Mod](Flans Mod-1.7.10-4.10.0.jar) 
    UCHIJA  fossil{1.7.10 Build 7.2.1} [Fossils and Archeology Revival](Fossils_Archeology_Revival-1.7.10_Build-7.2.1.jar) 
    UCHIJA  GalacticraftCore{3.0.12} [Galacticraft Core](GalacticraftCore-1.7-3.0.12.368.jar) 
    UCHIJA  GalacticraftMars{3.0.12} [Galacticraft Planets](Galacticraft-Planets-1.7-3.0.12.368.jar) 
    UCHIJA  gregtech{MC1710} [GregTech](gregtech_1.7.10-5.09.08.jar) 
    UCHIJA  HardcoreDarkness{1.6} [Hardcore Darkness](HardcoreDarkness-MC1.7.10-1.6.jar) 
    UCHIJA  HelpFixer{1.0.7} [HelpFixer](HelpFixer-1.0.7.jar) 
    UCHIJA  HardcoreQuesting{The Journey (4.3.0)} [Hardcore Questing Mode](HQM-The Journey %284.3.0%29.jar) 
    UCHIJA  IC2NuclearControl{2.2.5a-GoingForTheKill} [Nuclear Control 2](IC2NuclearControl-2.2.5a-GoingForTheKill.jar) 
    UCHIJA  IngameAccountSwitcher{bp1.7.10(2.2.2.0)} [In-Game Account Switcher](In-Game Account Switcher bp1.7.10%282.2.2.0%29.jar) 
    UCHIJA  LoreExp{1.0.5} [Lore Expansion](LoreExpansion-1.7.10-1.0.5.B29.jar) 
    UCHIJA  MineTweaker3{3.0.10} [MineTweaker 3](MineTweaker3-1.7.10-3.0.10.jar) 
    UCHIJA  MobProperties{0.4.1} [Mob Properties](MobProperties-1.7.10-0.4.2.jar) 
    UCHIJA  modelcitizens{1.0.1} [Model Citizens](ModelCitizens-mc1.7.10-1.0.1.jar) 
    UCHIJA  modtweaker2{0.9.4} [Mod Tweaker 2](ModTweaker2-0.9.4.jar) 
    UCHIJA  musicchoices{1.2_for_1.7.10} [Music Choices](MusicChoices-1.2_for_1.7.10.jar) 
    UCHIJA  NBTEdit{1.7.2.2} [In-game NBTEdit](NBTEdit_1.7.10.jar) 
    UCHIJA  Netherless{0.9.0} [Netherless](Netherless-0.9.0.jar) 
    UCHIJA  RedLogic{59.1.11} [RedLogic](redlogic-59.1.11.jar) 
    UCHIJA  OpenComputers{1.5.18.36} [OpenComputers](OpenComputers-MC1.7.10-1.5.18.36-universal.jar) 
    UCHIJA  PerfectSpawn{1.1} [Perfect Spawn](PerfectSpawn-1.1.jar) 
    UCHIJA  SpawnCommands{2.2.2} [SpawnCommands](SpawnCommands-2.2.2-mc1.7.10-forge.jar) 
    UCHIJA  TabulaRasa{1.7.10R1.0.1} [Tabula Rasa](TabulaRasa-[1.7.10]1.0.1-3.jar) 
    UCHIJA  TerrainControl{2.6.3} [Terrain Control](TerrainControl-2.6.3 .jar) 
    UCHIJA  erebus{0.3a} [Erebus](TheErebus-0.3a.jar) 
    UCHIJA  TML{4.0.1} [TooMuchLoot](TooMuchLoot-1.7.10-4.0.1.B0.jar) 
    UCHIJA  worldedit{6.0-beta-01} [WorldEdit](worldedit-forge-mc1.7.10-6.0-beta-01.jar) 
    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.2.12422 Compatibility Profile Context 13.152.1.1000' Renderer: 'AMD Radeon HD 7520G N HD 7520G + HD 7500/7600  7500/7600 Dual Graphics'
    AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
    AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:OFF, BC:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:OFF, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
    Launched Version: 1.7.10
    LWJGL: 2.9.1
    OpenGL: AMD Radeon HD 7520G N HD 7520G + HD 7500/7600  7500/7600 Dual Graphics GL version 4.2.12422 Compatibility Profile Context 13.152.1.1000, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: [ZT_1.3.0_GT5.zip, endtime.zip]
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by Tmtravlr** [comment]
Hmm, do you have music choices installed on the server? It's a client side mod, so it should never be on the server or it will cause crashes. Or is it your client crashing (you didn't specify)?

**Comment by Alessandro404** [comment]
Yes. Indeed I installed this mod on the server one time... circa one week ago, but I quickly fixed that pretty much immediately.

This crash is from the client, and happens only when i eat a cabbage on a Galacticraft dimension.

my firend told me about the cabbage  crash and I replicated that  on our server also, he told me about a similar crash when he try to listen the records of the mod "Fossils and Archeology Revival"

One detail. When we put this mod on the server, the server never crashed. The only difference was that the client of the person that tried to eat that cabbage crashed, and every other one was kicked from the server for a second.

**Comment by Tmtravlr** [comment]
Hmm that doesn't sound right. Music choices shouldn't be able to affect other clients, since it doesn't interact with the server at all (and can't possibly unless another mod is interfering with it).

And that's interesting about the fossils and archeology records. I remember playing one on a server just the other day with Music Choices installed with no problems, so there must be something else going on.

I've taken a look at the code, and it seems like the crash is caused by an item (probably the cabbage) that doesn't exist while the animation (eating animation I assume) is updating. I'm not sure why that would happen...

If possible, try running a small server with just Galacticraft and the mod with the cabbage. Then connect to it with music choices (and maybe without as well) as well and see if you get any crashes.
